// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnOVCINxhgQx696kOF--3GPJZibNlrVGM',
    appId: '1:50313495351:web:f71bae3da6e80602c990b2',
    messagingSenderId: '50313495351',
    projectId: 'pusat-aki-palembang',
    authDomain: 'pusat-aki-palembang.firebaseapp.com',
    storageBucket: 'pusat-aki-palembang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmgNYVkdgWAhc00kKuUGiUYIcCpDCq3J0',
    appId: '1:50313495351:ios:916e7e349add73c6c990b2',
    messagingSenderId: '50313495351',
    projectId: 'pusat-aki-palembang',
    storageBucket: 'pusat-aki-palembang.firebasestorage.app',
    androidClientId: '50313495351-de9nbsjadj45pqoq96sse81jksrhpmbf.apps.googleusercontent.com',
    iosClientId: '50313495351-554c7bd42hohramt3c46foajokif3j9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectUas',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi8BRhGScqoSD2IInYAAe-L_sXshYL-Z0',
    appId: '1:50313495351:android:24c43bebb48d57e4c990b2',
    messagingSenderId: '50313495351',
    projectId: 'pusat-aki-palembang',
    storageBucket: 'pusat-aki-palembang.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnOVCINxhgQx696kOF--3GPJZibNlrVGM',
    appId: '1:50313495351:web:b9850650bfffb41bc990b2',
    messagingSenderId: '50313495351',
    projectId: 'pusat-aki-palembang',
    authDomain: 'pusat-aki-palembang.firebaseapp.com',
    storageBucket: 'pusat-aki-palembang.firebasestorage.app',
  );

}